-- MySQL Script generated by MySQL Workbench
-- Fri Mar 19 18:54:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lola` ;

-- -----------------------------------------------------
-- Schema lola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lola` DEFAULT CHARACTER SET utf8 ;
USE `lola` ;

-- -----------------------------------------------------
-- Table `lola`.`Sectors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lola`.`Sectors` ;

CREATE TABLE IF NOT EXISTS `lola`.`Sectors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(41) NULL,
  `sector` VARCHAR(97) NULL,
  `semester` VARCHAR(97) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lola`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lola`.`Users` ;

CREATE TABLE IF NOT EXISTS `lola`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(41) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lola`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lola`.`Courses` ;

CREATE TABLE IF NOT EXISTS `lola`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(41) NULL,
  `name` VARCHAR(97) NULL,
  `picture` VARCHAR(241) NULL,
  `sector` INT NOT NULL,
  `admin` INT NOT NULL,
  `display` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`, `sector`, `admin`),
  INDEX `fk_Courses_Users_idx` (`admin` ASC),
  INDEX `fk_Courses_Sectors1_idx` (`sector` ASC),
  CONSTRAINT `fk_Courses_Users`
    FOREIGN KEY (`admin`)
    REFERENCES `lola`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Sectors1`
    FOREIGN KEY (`sector`)
    REFERENCES `lola`.`Sectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lola`.`Softwares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lola`.`Softwares` ;

CREATE TABLE IF NOT EXISTS `lola`.`Softwares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(97) NULL,
  `version` VARCHAR(17) NULL,
  `tuto` VARCHAR(241) NULL,
  `setup` VARCHAR(241) NULL,
  `commentary` VARCHAR(241) NULL,
  `picture` VARCHAR(241) NULL,
  `Softwarescol` VARCHAR(45) NULL,
  `course` INT NOT NULL,
  `display` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `course`),
  INDEX `fk_Softwares_Courses1_idx` (`course` ASC),
  CONSTRAINT `fk_Softwares_Courses1`
    FOREIGN KEY (`course`)
    REFERENCES `lola`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lola`.`SuperAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lola`.`SuperAdmins` ;

CREATE TABLE IF NOT EXISTS `lola`.`SuperAdmins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` INT NOT NULL,
  PRIMARY KEY (`id`, `login`),
  INDEX `fk_SuperAdmins_Users1_idx` (`login` ASC),
  CONSTRAINT `fk_SuperAdmins_Users1`
    FOREIGN KEY (`login`)
    REFERENCES `lola`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO lolaUser;
 DROP USER lolaUser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'lolaUser' IDENTIFIED BY '3R]IuZgx3%=2';

-- GRANT EXECUTE ON ROUTINE `lola`.* TO 'lolaUser';
GRANT EXECUTE ON `lola`.* TO 'lolaUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
